### ISSUE TITLE
Issue with bveq

### ISSUE THREAD

**Issue by nano-o** [pmatos/racket-bv#2]
I think this might a bug:
```
Welcome to DrRacket, version 8.3 [cs].
Language: racket, with debugging; memory limit: 512 MB.
> (require bv)
> (bveq (bv #x3f0c34bf93adf121 64)
        (bv #x3f0c34bf93adf121 64))
#f
```

**Comment by sorawee** [comment]
IIUC, this bug occurs because `memoize` can't process bignums correctly.

But also, I personally would avoid memoizing `bv`, even if it works. It's OK to memoize `bitvector` instances since there are only a few of them, but a long computation on `bv` that intuitively could take constant space might take linear space instead from filling up the memoization table, which is undesirable. Note that Rosette does _not_ memoize `bv`.

**Comment by pmatos** [comment]
Thanks @nano-o , I will take a look.
